name: Fluid Simulation Pipeline (Without Blender)

on:
  push:
  workflow_dispatch:

jobs:
  fluid-simulation:
    runs-on: ubuntu-latest
    steps:

      # 1️⃣ Step: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Step: Set Up Python (Fix PySPH Issues)
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3️⃣ Step: Install System Dependencies
      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip ffmpeg vtk

      # 4️⃣ Step: Install Python Dependencies
      - name: Install Python Packages
        run: |
          pip install -r requirements.txt
          echo "✅ Python dependencies installed successfully."

      # 5️⃣ Step: Run Fluid Simulation
      - name: Execute Fluid Simulation
        run: python3 src/fluid_simulation.py

      # 6️⃣ Step: Verify Simulation Output
      - name: Ensure Simulation Output Exists
        run: |
          if [ -f data/testing-input-output/fluid_dynamics_animation.json ]; then
            echo "✅ Simulation output generated successfully."
          else
            echo "❌ ERROR: Fluid simulation output missing!"
            exit 1
          fi

      # 7️⃣ Step: Render Simulation Frames
      - name: Render Frames Using PyVista
        run: python3 src/render_simulation.py

      # 8️⃣ Step: Generate Video from Frames
      - name: Create Final Video
        run: |
          chmod +x src/create_video.sh
          ./src/create_video.sh

      # 9️⃣ Step: Upload Video as Artifact
      - name: Upload Generated Video
        uses: actions/upload-artifact@v3
        with:
          name: simulation_final_video.mp4
          path: simulation_final_video.mp4

      # 🔟 Step: Run Validation & Tests
      - name: Run Unit Tests
        run: pytest tests/test_input_validation.py --verbose

      - name: Run Simulation Tests
        run: pytest tests/test_simulation_process.py --verbose

      - name: Run Video Rendering Tests
        run: pytest tests/test_video_generation.py --verbose

      - name: Run Optical Flow Analysis
        run: pytest tests/test_optical_flow.py --verbose
