name: Generate Video from PNG Frames

on:
  push:
    branches:
      - "main"
      - "master"
  workflow_dispatch: # Allows manual triggering

jobs:
  create_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dropbox Python SDK
        run: pip install dropbox

      - name: Make `download_from_dropbox.sh` Executable
        run: chmod +x src/download_from_dropbox.sh

      - name: Download PNG Frames from Dropbox
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: src/download_from_dropbox.sh

      - name: Set Video Generation Parameters
        id: set_params
        run: |
          INPUT_FRAMES_DIR="data/testing-input-output/turbine_animation_frames"
          OUTPUT_VIDEO_PATH="data/testing-input-output/turbine_flow_animation.mp4"
          DESIRED_FPS="10"

          echo "INPUT_DIR=${INPUT_FRAMES_DIR}" >> "$GITHUB_ENV"
          echo "OUTPUT_FILE=${OUTPUT_VIDEO_PATH}" >> "$GITHUB_ENV"
          echo "FPS=${DESIRED_FPS}" >> "$GITHUB_ENV"

      - name: Convert PNG Frames to Video with FFmpeg
        run: |
          echo "FFmpeg: Creating video from all PNG files in $INPUT_DIR at $FPS FPS"
          
          mkdir -p "$(dirname "$OUTPUT_FILE")"

          # Ensure old output file is removed to avoid overwrite prompt
          rm -f "$OUTPUT_FILE"

          ffmpeg -y -framerate "$FPS" -pattern_type glob -i "$INPUT_DIR/*.png" \
                 -c:v libx264 -preset medium -crf 23 -pix_fmt yuv420p \
                 "$OUTPUT_FILE"
          
          echo "✅ FFmpeg conversion complete."

      - name: Debug Generated Video File
        run: |
          echo "🔍 Checking if video file exists..."
          if [ -f "$OUTPUT_FILE" ]; then
            echo "✅ Video file exists: $OUTPUT_FILE"
          else
            echo "❌ ERROR: Expected output file '$OUTPUT_FILE' does not exist."
            exit 1
          fi
          
          echo "📂 Listing files in output directory..."
          ls -R "$(dirname "$OUTPUT_FILE")"

      - name: Make `upload_to_dropbox.sh` Executable
        run: chmod +x src/upload_to_dropbox.sh

      - name: Upload Generated Video to Dropbox
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          echo "📤 Uploading video file to Dropbox..."
          python3 src/upload_to_dropbox.py \
            "$OUTPUT_FILE" \
            "/engineering_simulations_pipeline/turbine_flow_animation.mp4" \
            "$REFRESH_TOKEN" \
            "$APP_KEY" \
            "$APP_SECRET"



