name: Generate Video from PNG Frames

on:
  push:
    branches:
      - "main"
      - "master"
  workflow_dispatch: # Allows manual triggering

jobs:
  create_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Set Video Generation Parameters
        id: set_params
        run: |
          INPUT_FRAMES_DIR="data/testing-input-output/turbine_animation_frames"
          OUTPUT_VIDEO_PATH="data/testing-input-output/turbine_flow_animation.mp4"
          DESIRED_FPS="10"

          echo "INPUT_DIR=${INPUT_FRAMES_DIR}" >> "$GITHUB_ENV"
          echo "OUTPUT_FILE=${OUTPUT_VIDEO_PATH}" >> "$GITHUB_ENV"
          echo "FPS=${DESIRED_FPS}" >> "$GITHUB_ENV"

      - name: Convert PNG Frames to Video with FFmpeg
        run: |
          echo "FFmpeg: Creating video from all PNG files in $INPUT_DIR at $FPS FPS"
          
          mkdir -p "$(dirname "$OUTPUT_FILE")"

          ffmpeg -framerate "$FPS" -pattern_type glob -i "$INPUT_DIR/*.png" \
                 -c:v libx264 -preset medium -crf 23 -pix_fmt yuv420p \
                 "$OUTPUT_FILE"
          
          echo "✅ FFmpeg conversion complete."

      - name: Commit and Push Generated Video
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }} 
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.email "${GIT_USER_EMAIL}"

          cd "$GITHUB_WORKSPACE"

          if [ -f "$OUTPUT_FILE" ]; then
            git add "$OUTPUT_FILE"
            git commit -m "Auto-update: Generated CFD visualization video"
            git push origin HEAD
          else
            echo "❌ No video file detected, skipping commit."
          fi
